### ISSUE TITLE
No graph in the widget

### ISSUE THREAD

**Issue by bernaxa** [jorgemorgado/dashing-polarchart#1]
Hello,

I'm trying the polarchart in dashing, but no graph is displayed in the widget, only the title and more-info.

This is the generated html for the "graph part":

`<iframe style="width: 100%; display: block; border: 0px none; height: 0px; margin: 0px; position: absolute; left: 0px; right: 0px; top: 0px; bottom: 0px;" class="chartjs-hidden-iframe"></iframe><canvas style="width: 300px; height: 305px;" width="391" height="397" class="chart-area"></canvas>
`

Is there something i can try to "debug" ?

Thanks!

**Comment by jorgemorgado** [comment]
You should be able to debug the issue using your browser's developer tools, Javascript console, etc. Please note [this issue](https://github.com/jorgemorgado/dashing-linechart/issues/1), where other users reported a similar issue. One user reported the problem was the browser (not working in Firefox but working fine with Chrome/Chromium). In your HTML output, you have the canvas being created just fine, so have a look at your Javascript console for possible errors.

**Comment by bernaxa** [comment]
You,re right. I'm getting a javascript error. 

`application.js:26052 Uncaught TypeError: (intermediate value).PolarArea is not a function`

I've tried to load manually the Chart.min.js from layout.erb, and also in Firefox / Chrome ...

so the error comes form the polar_chart.coffee, when trying to do the

`@myChart = new Chart(@ctx).PolarArea(@myData, $.extend({
`

but I don't know what could be the problem ...

Thanks again!

**Comment by bernaxa** [comment]
"solved". the problem was I downloaded v2 of Chart.min.js, but after "downgrading" to 1.0.2 from here:

https://cdnjs.com/libraries/Chart.js/1.0.2

the chart is rendered, but with that version we can't use "labels" functionality that is present in v2

the explanation to the problem is that the method of instantiating a chart has changed in v2:

https://github.com/chartjs/Chart.js/issues/1244
